name: media_kit_libs_macos_video
description: macOS package providing video (& audio) native libraries for package:media_kit.
version: 1.0.5
homepage: https://github.com/alexmercerind/media_kit.git
repository: https://github.com/alexmercerind/media_kit.git
funding:
  - https://www.github.com/sponsors/alexmercerind

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: MediaKitLibsMacosVideoPlugin
